### ISSUE TITLE
Compatibility issue with Astra Pro

### ISSUE THREAD

**Issue by Stanzilla** [xwp/pwa-wp#541]
Hey there, I noticed that there seems to be a compat issue with version 3.5.1 (and maybe earlier) of Astra Pro and the PWA plugin. As soon as Astra Pro is enabled, the service worker is no longer generated and throws an error 500. I will also report this to the Astra Team. Pretty sure it's not your issue, just wanted to post it as a heads up if people are Googling for it.

```
### wp-core ###

version: 5.7.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 2051
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 241.68 MB (253423680 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 72.93 MB (76469185 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 10.16 MB (10652899 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 161.86 MB (169721801 bytes)
database_size: 174.03 MB (182484992 bytes)
total_size: 660.66 MB (692752557 bytes)

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: Astra (astra)
version: 3.6.0
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, block-templates, astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, amp, widgets, menus
theme_path: /var/www/html/wp-content/themes/astra

### wp-server ###

server_architecture: Linux 5.4.0-74-generic x86_64
httpd_software: nginx/1.18.0
php_version: 8.0.7 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 512M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
server-headers: 
	server: nginx
	date: Thu, 17 Jun 2021 15:13:22 GMT
	content-type: text/html; charset=UTF-8
	vary: Accept-Encoding
	expires: Wed, 11 Jan 1984 05:00:00 GMT
	cache-control: no-cache, must-revalidate, max-age=0
	content-security-policy: Array
	link: Array
	x-frame-options: SAMEORIGIN
	x-xss-protection: 1; mode=block
	x-content-type-options: nosniff
	referrer-policy: no-referrer-when-downgrade
	strict-transport-security: max-age=31536000; includeSubDomains
	content-encoding: br

### wp-database ###

extension: mysqli
server_version: 8.0.25
client_version: mysqlnd 8.0.7

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
``` 

error log:

```
#8 /var/www/html/wp-includes/script-lo" while reading response header from upstream, client: 91.59.246.67, server: test.com, request: "GET /wp.serviceworker HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "test.com"
2021/06/17 15:18:07 [error] 199027#199027: *261844 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache.php on line 92PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache-base.php on line 431PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache-base.php on line 498PHP message: PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/wp-admin/includes/class-wp-filesystem-direct.php:66
Stack trace:
#0 /var/www/html/wp-admin/includes/class-wp-filesystem-direct.php(66): fopen()
#1 /var/www/html/wp-content/plugins/astra-addon/classes/class-astra-addon-filesystem.php(200): WP_Filesystem_Direct->put_contents()
#2 /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache-base.php(498): Astra_Addon_Filesystem->put_contents()
#3 /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache-base.php(336): Astra_Cache_Base->file_write()
#4 /var/www/html/wp-content/plugins/astra-addon/classes/cache/class-astra-cache.php(100): Astra_Cache_Base->write_assets()
#5 /var/www/html/wp-includes/class-wp-hook.php(292): Astra_Cache->setup_cache()
#6 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#8 /var/www/html/wp-includes/script-lo" while reading response header from upstream, client: 85.29.117.159, server: test.com, request: "GET /wp.serviceworker HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "test.com", referrer: "https://test.com/courses/"
```

**Edit** Their response: 

> As for now Astra doesn't have 100% compatibility with PWA plugin [...] In the meantime, I would suggest you try to roll back the PHP version to 7.4.6 (if possible) and test if it works. Currently, WordPress does not suggest using PHP 8 as of this time. [...]

**Comment by westonruter** [comment]
If there is a 500 error, then there's likely something in the PHP error log. Can you look for a fatal error in the PHP error log?

**Comment by Stanzilla** [comment]
> If there is a 500 error, then there's likely something in the PHP error log. Can you look for a fatal error in the PHP error log?

There was nothing about it in my php-fpm logs, what I posted above is from the nginx error log.

**Comment by westonruter** [comment]
Well, if there's a 500 error happening then there should be an error logged somewhere. Maybe [enable `WP_DEBUG_LOG`](https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_log).

**Comment by Stanzilla** [comment]
> Well, if there's a 500 error happening then there should be an error logged somewhere. Maybe [enable `WP_DEBUG_LOG`](https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_log).

But I posted the error log in my initial post?

**Comment by westonruter** [comment]
Oh, I missed that! I see the error log now. It does seem to be a bug in Astra.

**Comment by westonruter** [comment]
@Stanzilla Did you get a fix from Astra?

**Comment by Stanzilla** [comment]
> @Stanzilla Did you get a fix from Astra?

Nope, not yet. Do you want to close this or keep it open as a "heads-up" for other people who might come across it?

**Comment by westonruter** [comment]
Yeah, leave it open. Do you have an issue open with Astra?

**Comment by Stanzilla** [comment]
> Yeah, leave it open. Do you have an issue open with Astra?

Yeah via Email Support

**Comment by NicoHood** [comment]
Are there any updates on this?

**Comment by westonruter** [comment]
I'll close this for now. We can re-open if there is an action needed on the part of the plugin.

**Comment by NicoHood** [comment]
I am using it perfectly with the astra theme. Just to let you sleep in peace :)
